# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
